# Generated by Django 4.0 on 2023-04-28 17:57

import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=100)),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(78.3481, 17.44642), srid=4326)),
                ('xcor', models.FloatField(default=0)),
                ('ycor', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('AQ', 'AIR QUALITY'), ('WF', 'WATER FLOW'), ('WD', 'WATER DISTRIBUTION'), ('SL', 'SOLAR'), ('EM', 'ENERGY MONITORING'), ('SR-AQ', 'SMART ROOM - AQ'), ('SR-EM', 'SMART ROOM - EM'), ('SR-AC', 'SMART ROOM - AC'), ('SR-OC', 'SMART ROOM - OC'), ('CM', 'CROWD MONITORING'), ('WE', 'WEATHER'), ('WN', 'WISUN')], max_length=30)),
                ('visibility', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(default='-', max_length=100)),
                ('coordinates', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(17.44642, 78.3481), srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Node Locations',
            },
        ),
        migrations.CreateModel(
            name='TypeOfParameter',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.typeofparameter')),
            ],
            options={
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
